version: '3.8'

services:
  learn_engine:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./resource:/app/resource
      - ./app/data:/app/data
    env_file:
      - .env
    environment:
      - QUIZ_DATA_PATH=/app/data
      - RESOURCE_PATH=/app/resource
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  quiz_data:
    driver: local